/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ga_nurupeaches_imgmap_natives_NativeVideo */

#ifndef _Included_ga_nurupeaches_imgmap_natives_NativeVideo
#define _Included_ga_nurupeaches_imgmap_natives_NativeVideo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ga_nurupeaches_imgmap_natives_NativeVideo
 * Method:    read
 * Signature: (JLjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_ga_nurupeaches_imgmap_natives_NativeVideo_read
  (JNIEnv *, jobject, jlong, jobject, jobject);

/*
 * Class:     ga_nurupeaches_imgmap_natives_NativeVideo
 * Method:    getSource
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ga_nurupeaches_imgmap_natives_NativeVideo_getSource
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ga_nurupeaches_imgmap_natives_NativeVideo
 * Method:    newNativeVideo
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ga_nurupeaches_imgmap_natives_NativeVideo_newNativeVideo
  (JNIEnv *, jobject, jstring);

/*
 * Class:     ga_nurupeaches_imgmap_natives_NativeVideo
 * Method:    getWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ga_nurupeaches_imgmap_natives_NativeVideo_getWidth
  (JNIEnv *, jobject, jlong);

/*
 * Class:     ga_nurupeaches_imgmap_natives_NativeVideo
 * Method:    getHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_ga_nurupeaches_imgmap_natives_NativeVideo_getHeight
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
