/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ga_nurupeaches_imgmap_natives_NativeVideo */

#ifndef _Included_ga_nurupeaches_imgmap_natives_NativeVideo
#define _Included_ga_nurupeaches_imgmap_natives_NativeVideo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ga_nurupeaches_imgmap_natives_NativeVideo
 * Method:    read
 * Signature: (JLga/nurupeaches/imgmap/natives/NativeCallbackHandler;)V
 */
JNIEXPORT void JNICALL Java_ga_nurupeaches_imgmap_natives_NativeVideo_read
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     ga_nurupeaches_imgmap_natives_NativeVideo
 * Method:    newNativeVideo
 * Signature: (Ljava/lang/String;)J
 */
JNIEXPORT jlong JNICALL Java_ga_nurupeaches_imgmap_natives_NativeVideo_newNativeVideo
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
